<?php

declare(strict_types=1);
namespace Magmi\Gui\Installer;

use Magmi\Core\Config\Profile;
use Magmi\Core\Config\ProfileManager;

final class ApplicationInstaller
{
    public function initialize(string $base, string $autoload): void
    {
        if (!is_file($autoload)) {
            throw new \RuntimeException('Composer autoload.php was not found.');
        }
        $base = $this->prepareBase($base);
        $entry = $base . '/public/index.php';
        if (file_exists($entry) && !str_contains((string) file_get_contents($entry), '// Generated by magmi-gui')) {
            throw new \RuntimeException('An existing public/index.php would be overwritten. Use a separate application directory.');
        }
        foreach (['public', 'data/config', 'plugins'] as $dir) {
            $this->directory($base . '/' . $dir);
        }
        $profiles = new ProfileManager($base . '/data/config');
        if ($profiles->load('Default') === null) {
            $profiles->save(new Profile('Default'));
        }
        $code = "<?php\ndeclare(strict_types=1);\n// Generated by magmi-gui\n";
        $code .= 'define(\'MAGMI_GUI_BASE_DIR\', dirname(__DIR__));' . "\n";
        $code .= 'require ' . var_export(realpath($autoload), true) . ";\n";
        $code .= "if (session_status() === PHP_SESSION_NONE) {\n    session_start(['cookie_httponly' => true, 'cookie_samesite' => 'Lax', 'use_strict_mode' => true]);\n}\n";
        $code .= "(new \\Magmi\\Gui\\App\\Router())->dispatch();\n";
        $this->write($entry, $code);
        if (!file_exists($base . '/public/.htaccess')) {
            $this->write($base . '/public/.htaccess', "Options -Indexes\nRewriteEngine On\nRewriteCond %{REQUEST_FILENAME} !-f\nRewriteCond %{REQUEST_FILENAME} !-d\nRewriteRule ^ index.php [L]\n");
        }
        $this->publishAssets($base);
    }

    public function publishAssets(string $base): void
    {
        $base = $this->prepareBase($base);
        foreach (['css', 'js'] as $kind) {
            $source = dirname(__DIR__, 2) . '/public/' . $kind;
            $files = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($source, \FilesystemIterator::SKIP_DOTS));
            foreach ($files as $file) {
                if (!$file->isFile()) { continue; }
                $target = $base . '/public/' . $kind . '/' . substr($file->getPathname(), strlen($source) + 1);
                $this->directory(dirname($target));
                $this->write($target, (string) file_get_contents($file->getPathname()));
            }
        }
    }

    private function prepareBase(string $base): string
    {
        if ($base === '' || !str_starts_with($base, DIRECTORY_SEPARATOR)) {
            throw new \InvalidArgumentException('Use an absolute --base-dir path.');
        }
        return rtrim($base, '/\\');
    }

    private function directory(string $path): void
    {
        if (!is_dir($path) && !mkdir($path, 0755, true) && !is_dir($path)) {
            throw new \RuntimeException('Cannot create directory: ' . $path);
        }
    }

    private function write(string $path, string $contents): void
    {
        if (file_put_contents($path, $contents, LOCK_EX) === false) {
            throw new \RuntimeException('Cannot write file: ' . $path);
        }
    }
}
